### PR TITLE
add notebook to train resnet on esc50

### PR DESCRIPTION
**Pull request by PariaValizadeh**

### CODE REVIEW

**Review by raphaelschwinger — COMMENTED** [review]
Hey @PariaValizadeh,
Thanks for your PR. To have the code in our repo a bit more readable, could you:
- move the notebook into a folder (e.g. `/notebooks/misc`)
- remove unneeded imports (VS Code should give you a hint on those
- remove the "is cuda available code", if you want you can add this to our Notion server page
- add some markdown comments / headlines
- add a section on evaluation
- rename the notebook to be a bit more readable, e.g `train-ResNet-on-ESC50.ipynb`

Thanks for your work!

**Comment by PariaValizadeh** [comment]
Hey Raphael,

For the evaluation part of a model, one way is to use the terminal and call
the train.py and the experiment. I remember that you gave me another code
for implementing evaluation in notebook(the jupyter file) but I can not
find it in my computer and also in the tutorial. Could you please tell me
where I can find it? I want to use the trained model and feed it with a
test sample(or all the test samples) to see how it works in my notebook.
Thank you
best regards,
Paria

**Comment by PariaValizadeh** [comment]
Hey Raphael,

I was just trying to eval the resnet on HSN and esc50 again to see if it
works by this command "python birdset/train.py
'experiment=local/HSN/resnet.yaml'" and I encountered an error for just
multilabel one then I tried the efficient experience and it has the same
one.
this is an error :
 Instantiate model
<birdset.modules.models.efficientnet.EfficientNetClassifier>
Error executing job with overrides:
['experiment=local/HSN/efficientnet.yaml']
Error locating target
'birdset.module.metrics.multilabel.MultilabelMetricsConfig', set env var
HYDRA_FULL_ERROR=1 to see chained exception.
full_key: module.metrics

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Do you have any idea why this happened?

**Comment by raphaelschwinger** [comment]
Hey Paria,

You can use trainer.fit Take a look at the lightning docs ;)

> Am 15.04.2024 um 17:08 schrieb PariaValizadeh ***@***.***>:
> 
> 
> Hey Raphael, 
> 
> For the evaluation part of a model, one way is to use the terminal and call 
> the train.py and the experiment. I remember that you gave me another code 
> for implementing evaluation in notebook(the jupyter file) but I can not 
> find it in my computer and also in the tutorial. Could you please tell me 
> where I can find it? I want to use the trained model and feed it with a 
> test sample(or all the test samples) to see how it works in my notebook. 
> Thank you 
> best regards, 
> Paria 
> 
> On Mon, Apr 15, 2024 at 11:34 AM paria valizadeh ***@***.***> 
> wrote: 
> 
> > Hey Raphael, 
> > I will make the change and let you know 
> > Best regards, 
> > 
> > 
> > On Mon, Apr 15, 2024 at 9:31 AM Raphael Schwinger <

**Comment by raphaelschwinger** [comment]
There was a small type, fixed in https://github.com/DBD-research-group/BirdSet/commit/856c51f67a9a65569ecda8427aa050cf2a4f51d9
Thanks for catching it!

> Am 16.04.2024 um 09:19 schrieb PariaValizadeh ***@***.***>:
> 
> 
> Hey Raphael, 
> 
> I was just trying to eval the resnet on HSN and esc50 again to see if it 
> works by this command "python birdset/train.py 
> 'experiment=local/HSN/resnet.yaml'" and I encountered an error for just 
> multilabel one then I tried the efficient experience and it has the same 
> one. 
> this is an error : 
> Instantiate model 
> <birdset.modules.models.efficientnet.EfficientNetClassifier> 
> Error executing job with overrides: 
> ['experiment=local/HSN/efficientnet.yaml'] 
> Error locating target 
> 'birdset.module.metrics.multilabel.MultilabelMetricsConfig', set env var 
> HYDRA_FULL_ERROR=1 to see chained exception. 
> full_key: module.metrics 
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace. 
> 
> Do you have any idea why this happened? 
> 
> On Mon, Apr 15, 2024 at 5:07 PM paria valizadeh ***@***.***> 
> wrote: 
> 
> > Hey Raphael, 
> > 
> > For the evaluation part of a model, one way is to use the terminal and 
> > call the train.py and the experiment. I remember that you gave me another 
> > code for implementing evaluation in notebook(the jupyter file) but I can 
> > not find it in my computer and also in the tutorial. Could you please tell 
> > me where I can find it? I want to use the trained model and feed it with a 
> > test sample(or all the test samples) to see how it works in my notebook. 
> > Thank you 
> > best regards, 
> > Paria 
> > 
> > On Mon, Apr 15, 2024 at 11:34 AM paria valizadeh <

**Pull request closed without merging**
