### PR TITLE
last Update birdset pipline tutorial

### PR DESCRIPTION
**Pull request by PariaValizadeh**
add evaluation and visalization part to pipline

### CODE REVIEW

**Comment by raphaelschwinger** [comment]
@PariaValizadeh Is this PR still valid? Could you update the title and description?

**Comment by PariaValizadeh** [comment]
I  changed the title

**Comment by PariaValizadeh** [comment]
I update the tutorial completely in this commit f270715a2938acd1074796187bfe141e6ee7766f
also I  creat another pull request because i split tthe new part that I added to birdset tutorial to a new file again here 358ae92e0b8eeb0a65426dc2c51bf967a6627911 , so now you have 2 files which we can choose the one we think is better. I hope I didn't make it complecated.

**Comment by raphaelschwinger** [comment]
@PariaValizadeh This is a duplicate of #204

**Pull request closed without merging**
