### PR TITLE
Tutorial for initialing evaluating visalizing model seperatly

### PR DESCRIPTION
**Pull request by PariaValizadeh**
in the previous pull request i added a audiovisualization file which was by mistake. sorry about that. this is a correct file which we discuss to make it seperate from birdset_tutorial.

## Roadmap
- [x] get datamodule
- [x] prepare trainer
- [x] prepare model
- [x] initialize model
- [x] get sample from testdataset
- [x] visualization
- [x] train model
- [x] eval model
- [x] inference on one sample
- [x] get ebirdcode from one sample
- [x] convert prediction output to class label name

### CODE REVIEW

**Comment by PariaValizadeh** [comment]
@raphaelschwinger this is the correct comit. I could not delet the others 69c91ff263f6068814db38f07c0be1982bf57b23

**Comment by PariaValizadeh** [comment]
I tried to clean all pr c272b30326d4d552310dc51b19779dba4ecbbd11

**Comment by lurauch** [comment]
@PariaValizadeh could you please solve the conflicts?

**Comment by PariaValizadeh** [comment]
> @PariaValizadeh could you please solve the conflicts?

Thank you for your review. I fixed the conflicts. dc2d27ed3da3d01fdedc4870f69ac180a87da4e6

**Pull request closed without merging**
