### PR TITLE
Add resnet esc50 notebook

### PR DESCRIPTION
**Pull request by PariaValizadeh**
train resnet on esc50 to close [issue](https://www.notion.so/Get-familiar-with-BirdSet-pipeline-41b59a64fe11407b8b102bad0d86f767?pvs=4)

## Roadmap
- [x] get datamodule
- [x] get trainer
- [x] initialize model
- [x] train model
- [x] eval model

### CODE REVIEW

**Comment by raphaelschwinger** [comment]
@PariaValizadeh Here are a lot more files changed then just the notebook for training resnet on esc50. Could you tidy up the PR?

**Comment by PariaValizadeh** [comment]
I tried tp clean up pr  b7f24a9374f5ad95e1abc0605ee62c8a8eb06f5a

**Comment by lurauch** [comment]
@PariaValizadeh Could you please correct some spelling mistakes? e.g. beginers = beginners (there are also a few in the respective notebooks). Additionally, please think of a shorter and more structured naming convention. Right now, it's quite confusing. Thanks! :)

**Comment by PariaValizadeh** [comment]
> @PariaValizadeh Could you please correct some spelling mistakes? e.g. beginers = beginners (there are also a few in the respective notebooks). Additionally, please think of a shorter and more structured naming convention. Right now, it's quite confusing. Thanks! :)

Thank you. I fixed those. 167dc6134baf76fa1acd44c4824a9d1baff32e5f

**Review by lurauch — APPROVED** [review]

**Pull request merged**
